# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee8ec0a2346e3bba77010e691fc0c8530a8486ad4181869f40016f875a69dcd377eeb2ef389efc37d0f8584edef298798fe1b4a5ac6070d204caecc7e848aa27

test:
  secret_key_base: 78fd974e21716cc206cd17d826cb16afa691a83923c002418644031cee490ed74b18a506e8812432b2ff079b5d5ab8c1733f29a91193947921eb177d39c779bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
